### ISSUE TITLE
[TASK]  Hiwi Birthdate to Date Type

### ISSUE THREAD

**Issue by JuliaSelua** [reform-org/reform#116]
Estimated story points:

# Description
 
Change the Hiwi Birthdate Value from String to some kind of Date

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Bitte als Datentyp Long nehmen und dann mit den Methoden in Utils/Date von einem Datum dahin konvertieren.

**Comment by lukasschreiber** [comment]
https://github.com/reform-org/reform/pull/130 abhängig von diesem PR

**Comment by lukasschreiber** [comment]
Kann glaube ich jetzt bearbeitet werden, da das refactoren vermutlich kein großer Aufwand ist.

**Comment by JuliaSelua** [comment]
time: 3h
