### ISSUE TITLE
[TASK] Make it beautiful

### ISSUE THREAD

**Issue by JuliaSelua** [reform-org/reform#118]
Estimated story points:

# Description
 
Make the front end beautiful.

 

# Acceptance criteria

**Comment by JuliaSelua** [comment]
Dark Mode
Table view for mobile devices
Space between the buttons

**Comment by Oshgnacknak** [comment]
Tables need borders and more reasonable spacing.
Make tables use the full available screen size

**Comment by lukasschreiber** [comment]
@JuliaSelua wollen wir den Task nutzen um noch weitere UI Änderungen zu machen, oder wollen wir das lieber Kleinteiliger machen und einzelene Tasks für die Änderungen machen?

**Comment by mohe2015** [comment]
Denke einzelne Tasks ist sinnvoller.

**Comment by JuliaSelua** [comment]
time: 5h

**Comment by JuliaSelua** [comment]
time: 1h
