### ISSUE TITLE
[US] Synchronize between multiple clients

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#12]
Estimated story points: 8

# Description
 
As a user I want to synchronize the counter between multiple browser clients without needing a server.
If I want to host a session, I want to generate a token that I can share with my peers.
If I want to join, I want to receive a token from my peers use it in the application.

 

# Acceptance criteria

- A numeric input field can be synced between multiple clients.
- Changes made by any user also take place at any of their peers without requiring further user interaction.
- Any peer can join/leave the session at any time, i.e. there is no peer acting as a server.
- Concurrent changes from multiple clients are resolved without conflicts and correctly.

**Comment by mohe2015** [comment]
Closed by https://github.com/reform-org/reform/pull/33

**Comment by mohe2015** [comment]
11h

**Comment by Oshgnacknak** [comment]
time: 12h
