### ISSUE TITLE
[TASK] Multiple tabs in the same browser should also sync?

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#120]
Estimated story points:

# Description
 

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Das wäre cool

**Comment by lukasschreiber** [comment]
Oder zumindestens - falls sie das nicht tun - sollte eine Warnung kommen, dass man das Tool nur in einem Tab nutzen kann...

**Comment by mohe2015** [comment]
time: 7h

**Comment by mohe2015** [comment]
Duplicate of https://github.com/reform-org/reform/issues/260
