### ISSUE TITLE
[TASK] Unify link hrefs and .to navigation calls

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#142]
Estimated story points:

# Description
 

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
@mohe2015 könntest du bitte hier die Beschreibung ein bisschen ausführlicher machen?

**Comment by mohe2015** [comment]
https://github.com/reform-org/reform/blob/8aacdf6e8a4961ff7a64595951b1b05733666b16/js/src/main/scala/webapp/components/NavigationHeader.scala#L68-L76

This part is duplicated at many places. The `services.routing.to(UsersPage(), true)` knows where to route to so the `href` should be set based on the page you navigate to automatically. Maybe this could be extracted into a `NavigationLink` component

**Comment by JuliaSelua** [comment]
time: 1h
