### ISSUE TITLE
[US] Banner to show the user that the application does not work

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#151]
Estimated story points:

# Description
 
If writing to the localstorage or to indexeddb fails a banner should be displayed on top, stating, that the application is not compatible with this browser

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
https://daisyui.com/components/alert/ sowas in die Reichtung vielleicht...

**Comment by lukasschreiber** [comment]
Um zu checken ob das angezeigt werden muss würde ich glaube ich einfach einen testwert in den localstorage schreiben und schauen ob er es geschafft mit window.localStorage.setItem("test", "myTestString") und window.localStorage.getItem("test") != null

**Comment by mohe2015** [comment]
> Um zu checken ob das angezeigt werden muss würde ich glaube ich einfach einen testwert in den localstorage schreiben und schauen ob er es geschafft mit window.localStorage.setItem("test", "myTestString") und window.localStorage.getItem("test") != null

Not local storage but indexeddb. Also I think additionally we should check that the writes to the indexeddb itself don't fail but maybe not do that in this user story as that is probably more complicated to show and handle

**Comment by lukasschreiber** [comment]
Dann beides, localstorage failed bei ff auch und dann ist der discovery
server nicht nutzbar

**Comment by lukasschreiber** [comment]
@mohe2015 was ist hiermit eigentlich? Ist das erledigt durch die Fehlermeldungen in den Toasts?

**Comment by mohe2015** [comment]
Würde sagen, wir versuchen am anfang noch nen testwert in den storage zu schreiben, damit die User experience in firefox private tab besser ist. aber ansonsten ja. Den teil kann aber gerne Julia übernehmen, vmtl irgendwo in der Main z.b. nen testwert versuchen reinzuschreiben und wenn das failed ne meldung mit "vmtl nutzt du firefox im private tab, zumindest ist dein storage kaputt"

**Comment by JuliaSelua** [comment]
time: 8h

**Comment by JuliaSelua** [comment]
time: 1h
