### ISSUE TITLE
[TASK] Navigation Links Beautiful

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#153]
Estimated story points:

# Description
 
![image](https://user-images.githubusercontent.com/31158920/215345103-113b18b6-c570-461c-9f2e-fc8ef73f44f4.png)
Navigation links should be nested, e.g. there should be a Settings Tab with Payment Levels and Salary Changes below.

See here for the buttons:
https://daisyui.com/components/navbar/#responsive-dropdown-menu-on-small-screen-center-menu-on-large-screen

Please style accordingly to the rest in the branch connection - especially buttons should not be to thick, I created the class min-h-10 to force the min height to be reduced.

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
The buttons should not turn from white to purple on click, I think in this case a more suttle gray as in the demo would be nice

**Comment by lukasschreiber** [comment]
Please branch from connection, the branch should be in working order right now

**Comment by lukasschreiber** [comment]
What about focus:bg-slate-200

**Comment by JuliaSelua** [comment]
time: 6h

**Comment by JuliaSelua** [comment]
time: 1h
