### ISSUE TITLE
[TASK] Tooltips for buttons without Text

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#154]
Estimated story points:

# Description
 
![image](https://user-images.githubusercontent.com/31158920/215345392-70e4571d-8e75-4bbd-88c3-e4d93b38f874.png)
 small buttons like this one (currently only this one) should have tooltips. This one for example "Close Connection"

https://daisyui.com/components/tooltip/
 

# Acceptance criteria

**Comment by JuliaSelua** [comment]
time: 3.5h
