### ISSUE TITLE
[US] Make WebRTC work over the scary internet

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#165]
Estimated story points:

# Description
 
Probably a STUN server is needed. Maybe even a TURN server.

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Might be interesting: https://github.com/Atlantis-Software/node-turn

**Comment by lukasschreiber** [comment]
How can we say that a STUN Server is enough, doesn't that depend on the peers configuration? In my understanding you need a TURN server once one peer is behind a symmetric NAT. I think we should provide a TURN server and therefore sacrifice the p2p thing if you are connected over the internet and not just within the same network

**Comment by mohe2015** [comment]
> How can we say that a STUN Server is enough, doesn't that depend on the peers configuration? In my understanding you need a TURN server once one peer is behind a symmetric NAT. I think we should provide a TURN server and therefore sacrifice the p2p thing if you are connected over the internet and not just within the same network

Yeah, we should probably provide both for user friendlyness. If its possible I think it would be nice to show in the UI whether you are connected using a TURN server. also we need to ensure its access is restricted so nobody is using it for other purposes. additionally at a later stage the connection over the turn server probably needs to be authenticated using the webrtc peer certificates to prevent man in the middle.

**Comment by lukasschreiber** [comment]
Habe gerade keinen Bock auf Designen, ich installiere das ding mal auf meinem server (oder verusche es xD)

**Comment by lukasschreiber** [comment]
Verstehe ich es richtig, dass man hier quasi herausfinden muss ob man STUN oder TURN benötigt und wenn man es benötigt muss man die IP Adresse und das Port ermitteln und das entsprechend in die Session Description packen oder ist es komplizierter als das?

**Comment by lukasschreiber** [comment]
@mohe2015

**Comment by lukasschreiber** [comment]
Oder reicht es sogar die Daten als iceServer irgendwo zu übergeben? Weil die normale Webbrowser implementierung von WebRTC kann glaube ich selbst entscheiden was sie nutzt...

**Comment by mohe2015** [comment]
> Oder reicht es sogar die Daten als iceServer irgendwo zu übergeben? Weil die normale Webbrowser implementierung von WebRTC kann glaube ich selbst entscheiden was sie nutzt...

Sollte man irgendwo angeben können und dann sollte das gehen

**Comment by lukasschreiber** [comment]
https://www.scala-js.org/api/scalajs-dom/0.9.0/#org.scalajs.dom.experimental.webrtc.RTCConfiguration hier kann man das einfach bei loci.communicator.webrtc.offer(...) übergeben

**Comment by lukasschreiber** [comment]
time: 10h
