### ISSUE TITLE
[TASK] Salary Changes min Date

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#167]
Estimated story points:

# Description
 
The Datepicker in the salary changes page should have a min Date, so that it is not possible to create overlapping intervals

 

# Acceptance criteria

**Comment by mohe2015** [comment]
I think our AG wanted to be able to set values in the past. As there is only a start date I think its not possible to create overlapping intervals. We could still warn though if you add an entry that is before another entry.

**Comment by Oshgnacknak** [comment]
Invalided, as @mohe2015 pointed out
