### ISSUE TITLE
[TASK] Tables should be filterable

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#170]
Estimated story points:

# Description
 
It should be able to filter the table, currently it is not specified how far this filtering should go, e.g. which fields should be filterable

 

# Acceptance criteria

- [x] Textual Filter for Substrings
- [x] Min max filter for
  - [x] Ints
  - [x] Dates
- [x] Filter for boolean values

**Comment by mohe2015** [comment]
I think showing and hiding deleted should be the minimum. Otherwise probably things like filter per HiWi etc.

**Comment by lukasschreiber** [comment]
I think there shouldn't be too many entries but still I think it is a better UX if there is a option to filter the data, not every user might even know Ctrl+F as search

**Comment by lukasschreiber** [comment]
I think we should implement the filtering as it is in easycontracts, at least if we have the time to do so.

**Comment by Oshgnacknak** [comment]
Given the UIAttribute we might be able to render a costume input for each attribute. From this input we could derive a predicate on which we can then filter.

*Put some dottedness in there and ragnar will love it*

**Comment by lukasschreiber** [comment]
@Oshgnacknak ist der Task done? Also alles was von diesem Issue abgedeckt wird?

**Comment by Oshgnacknak** [comment]
closed by #204
