### ISSUE TITLE
[TASK] Style tables to fit in the overall aesthetics

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#171]
Estimated story points:

# Description
 
- [ ] #308
- [ ] #307
- [x] schicke Tabelle
- [x] schöne Buttons
- [ ] Title
- [x] schöne Input
- [x] #282
- [x] money, date Felder testen
- [ ] Konflikte von Select und Datum und Money Feldern #282
- [x] Doppelklick auf Feld soll Zeile editable machen
- [x] Buttons sollten vertikal mittig sein vmtl items-center oder sowas
- [x] Delete Modal hat den Wert erst nach einem page reload
- [x] Add Entity Button wird zweizeilig auf kleinen screens - add white-space: nowrap to add entity button
- [x] Fix tests to work with renamed buttons
- [x] table should have min snd max width per col and work on mobile

 

# Acceptance criteria

**Comment by JuliaSelua** [comment]
- [ ] Empty state
- [ ] Loading state
- [ ] schicke Tabelle
- [ ] schöne Buttons
- [ ] Title
- [ ] schöne Input

**Comment by lukasschreiber** [comment]
time: 15h
