### ISSUE TITLE
[TASK] Alert when new User has connected

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#172]
Estimated story points:

# Description
 
There should be a brief alert in the bottom right corner stating that a new user has connected. It should show the alias and the source and disappear after a short amount of time. The appearing and disappearing should be animated.

It should also be closable before the time has elapsed

The alert disposable system should be generic enought, that it is possible to send other alerts in the future

https://daisyui.com/components/toast/

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
@JuliaSelua hier können wir direkt unseren coolen Toaster anwenden, immer wenn eine neue Connection aufgebaut wird soll ne Benachrichtigung kommen in WebRTCService.scala Zeile 130 wird die neue remoteRef übergeben, nachdem eine Connection aufgebaut wurde, mit getInformation(remoteRef) bekommst du Infos über die Connection, unter anderem das alias und die Methode (manuell oder discovery) und falls du das auch anzeigen wolltest mit getConnectionMode(remoteRef) bekommst du den Modus (direct oder relay) als Future zurück... Vllt können wir den Toasts auch nicht nur Text sondern eine VNode übergeben, sodass wir dann formatierten Text anzeigen können... Damit könnte man zum Beispiel manuell iwie in einer zweiten Zeile ein bisschen kleiner und grau anzeigen oder so... aber kannst das auch erstmal einfach als ein Text machen.

**Comment by JuliaSelua** [comment]
time: 1h
