### ISSUE TITLE
[TASK] If there are unsaved changes the user should be asked to stay

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#191]
Estimated story points:

# Description
 
![image](https://user-images.githubusercontent.com/31158920/216120120-3d373e0f-e02e-4d9e-9d32-53c818426b1c.png)

 

# Acceptance criteria

**Comment by mohe2015** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by lukasschreiber** [comment]
time: 2h
