### ISSUE TITLE
[US] Use Service Worker so page works fully offline

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#195]
Estimated story points:

# Description
 

https://vite-pwa-org.netlify.app/guide/
https://vite-pwa-org.netlify.app/deployment/nginx.html

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Please elaborate (:

**Comment by mohe2015** [comment]
Browser can use the Service Worker API https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API to make a page fully available offline after you first loaded it. This means it also loads when the server is offline. We could use that to make our application truly offline first. 

https://web.dev/learn/pwa/workbox/

**Comment by lukasschreiber** [comment]
Thanks

**Comment by mohe2015** [comment]
time: 13h
