### ISSUE TITLE
[US] Navigation

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#20]
Estimated story points:

# Description
 
- As a user I want to be able to navigate between multiple pages.

 

# Acceptance criteria

- You navigate between multiple pages using a navigation bar.

**Comment by mohe2015** [comment]
Depends on https://github.com/reform-org/reform/issues/21

**Comment by mohe2015** [comment]
Fixed in https://github.com/reform-org/reform/pull/27

**Comment by mohe2015** [comment]
@lukasschreiber please write hour hours invested in a comment here

**Comment by lukasschreiber** [comment]
time: 2h 30min
