### ISSUE TITLE
[TASK] Seqnal

### ISSUE THREAD

**Issue by Oshgnacknak** [reform-org/reform#205]
Estimated story points:

# Description
 
We need helpers for types like `Signal[Seq[T]]` and `Seq[Signal[T]]`.
- `filter`
- `flatMap`

Basically, wherever there is a `flatten`, there should also be the need to refactor something
 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Ist das nicht auch schon drin @Oshgnacknak

**Comment by Oshgnacknak** [comment]
closed by #229

**Comment by Oshgnacknak** [comment]
Time: 10h
