### ISSUE TITLE
[TASK] Toaster

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#206]
Estimated story points:

# Description
 
A service that manages toast messages globally and displays them for a certain amount of time

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
https://daisyui.com/components/toast/

**Comment by lukasschreiber** [comment]
it would be nice to set an alert message to be "autodismissable" so critical messages must be dismissed by the user. An alert message should have a text, a type (success, warning, danger, ...) based on which the color/icon is set and a autodismissable property. If set to autodismissable the alert should disappear after a sepcified amount of time, maybe 20 sec or if the user closes it. If autodismissable is set to false the alert should stay visible until the user actively closes it. Multiple alerts should be able to be shown simultaneaously.

**Comment by lukasschreiber** [comment]
Btw I would love the component being called toaster xD then a call for a new alert could be toaster.make(...)

**Comment by JuliaSelua** [comment]
Fix on small screens and add alert to failures

**Comment by JuliaSelua** [comment]
time: 9h

**Comment by lukasschreiber** [comment]
time: 9h

**Comment by JuliaSelua** [comment]
time: 1h
