### ISSUE TITLE
[US] Implement CI builds

### ISSUE THREAD

**Issue by Oshgnacknak** [reform-org/reform#3]
Estimated story points: 3

# Description
 
Merges trigger automatic ci checks
 

# Acceptance criteria

- before every merge, the ci builds the project,
- a linter enforces style guides and
- the test suit passes

**Comment by mohe2015** [comment]
https://github.com/scala-steward-org/scala-steward-action

**Comment by mohe2015** [comment]
- build documentation?
- test coverage?
