### ISSUE TITLE
Loading state for tables

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#307]

**Comment by lukasschreiber** [comment]
For Tables

**Comment by mohe2015** [comment]
I would also be fine with closing this as the delay should be pretty short. Maybe instead we could improve that delay

**Comment by lukasschreiber** [comment]
Fine for meOn 28 Feb 2023 22:41, Moritz Hedtke ***@***.***> wrote:
I would also be fine with closing this as the delay should be pretty short. Maybe instead we could improve that delay
