### ISSUE TITLE
[TASK] Edit mode in tables is ugly

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#331]
Estimated story points:

# Description
 
weird distance to top, no border, color ist white, not the correct zebra color, row should be highlighted some how, to show the editing

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Many things should already be done, but I think there is still some issue witha weird top distance

**Comment by JuliaSelua** [comment]
time: 2.5h
