### ISSUE TITLE
[TASK] Manual connect may not work if you connect over public internet

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#394]
Estimated story points:

# Description
 

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Not fixable, info should be added

**Comment by mohe2015** [comment]
I think I had stun server issues but if that was not the case we should just document this or leave this. But we should definitely document that the tokens are only valid once

**Comment by lukasschreiber** [comment]
time: 30min
