### ISSUE TITLE
[US] Create User Account

### ISSUE THREAD

**Issue by Oshgnacknak** [reform-org/reform#41]
Estimated story points:

# Description
 
As a user, I want to create an account.
I want to specify the username, the role and a comment.
 

# Acceptance criteria

- If the information is valid, the new account is created and display in the list.
- The username must be unique, the role must not be empty. There are no restrictions on the comment.

**Comment by mohe2015** [comment]
Should be implemented in https://github.com/reform-org/reform/pull/50

**Comment by JuliaSelua** [comment]
Atm the username is not checked to be unique.

**Comment by JuliaSelua** [comment]
time: 4h
