### ISSUE TITLE
[US] Delete User Account

### ISSUE THREAD

**Issue by Oshgnacknak** [reform-org/reform#42]
Estimated story points:

# Description
 
As a user, I want to delete another users account.
 

# Acceptance criteria

- The user is deleted and all of their session are disconnected from the peek group.

**Comment by mohe2015** [comment]
Implementation may be by adding a boolean to the user properties that hides the user in the list but still syncs it. This allows undeletion. Should also be similar to https://github.com/reform-org/reform/issues/17

**Comment by mohe2015** [comment]
Closed by https://github.com/reform-org/reform/issues/42

**Comment by mohe2015** [comment]
time: 0.75h

**Comment by JuliaSelua** [comment]
AC before:The user is deleted and all of their session are disconnected from the peek group.
