### ISSUE TITLE
[TASK] Create Settingspage for Darkmode, Import, ...

### ISSUE THREAD

**Issue by lukasschreiber** [reform-org/reform#433]
Estimated story points:

# Description
 

 

# Acceptance criteria

**Comment by JuliaSelua** [comment]
what do you want to put on this page? or do you want to insert this @lukasschreiber

**Comment by lukasschreiber** [comment]
Darkmode select und die controls für export import und drop db jeweils mit erklärung

**Comment by JuliaSelua** [comment]
time: 6h

**Comment by JuliaSelua** [comment]
time: 1h
