### ISSUE TITLE
[TASK] Scrolling with open dropdowns is laggy on firefox

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#453]
Estimated story points:

# Description
 
> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!

 

# Acceptance criteria

**Comment by mohe2015** [comment]
I think positioning: fixed is at fault but that is needed so the popovers work in tables

**Comment by Oshgnacknak** [comment]
Cannot reproduce
