### ISSUE TITLE
[US] Getting used to Scala and REScala

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#5]
Estimated story points: 8
(note this user story was started before creating this github repository)

# Description
 
all team members get used to Scala and REScala

 

# Acceptance criteria

- every team member has a working development environment
with Scala and RESscala
- every team member has a fundamental understanding of Scala
and REScala
- the REScala Todolist example runs on every team members computer.

**Comment by mohe2015** [comment]
@lukasschreiber @Oshgnacknak @AntonBeasis @JuliaSelua please put the hours invested here


estimated hours: ~9 hours

**Comment by JuliaSelua** [comment]
estimated hours: ~10.5 hours

**Comment by Oshgnacknak** [comment]
estimated hours: ~11 hours

**Comment by mohe2015** [comment]
time: 9h

**Comment by lukasschreiber** [comment]
time: 10h
