### ISSUE TITLE
[US] CRUD for HiWis

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#53]
Estimated story points: 8

# Description
 
As a user I want to manage hiwis consisting of first name, last name, date of birth and email. By managing creating, editing and deleting is meant.

 

# Acceptance criteria

Hiwis can be created, edited and deleted.

**Comment by lukasschreiber** [comment]
Denk dran die Zeit hier zu tracken @JuliaSelua

**Comment by JuliaSelua** [comment]
time: 1.5h
