### ISSUE TITLE
documentation request: how to find PDF internal names

### ISSUE THREAD

**Issue by rmgk** [reform-org/reform#533]
As the contract pdfs in particular tend to change often (every time hiwi payments change, which tends to be once every other year or so), it would be good to have some documentation on how to figure out the labels (because they also change every time 😅). 
Maybe it exists somewhere and I did not see it?

**Comment by lukasschreiber** [comment]
There is no documentation inside of the app, should we add something to the README or do you think it would be better to have that directly on the payment level page?

**Comment by lukasschreiber** [comment]
While searching for a solution that is reporoducible cross platform and without paying money to Adobe I found that this is not really possible so I added a mini PDF inspector on the edit page, that lists all of the Field types and field names in the order of their appearance in the PDF. We have to read this data anyways, so why not just present it to the user. This should do the trick for most use cases, as the names are not completely random. https://github.com/reform-org/reform/pull/535
