### ISSUE TITLE
[US] Import / Export data

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#55]
Estimated story points: 5

# Description
 
As a user I want to be able to export all data

 

# Acceptance criteria

**Comment by mohe2015** [comment]
Maybe later a simpler data model which just exports the data itself.

**Comment by mohe2015** [comment]
E.g. An RGA would have terrible metadata which is really dependent on the metadata so a custom export for that would be better

**Comment by lukasschreiber** [comment]
time: 5h
