### ISSUE TITLE
[US] CRUD for Payment Levels

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#83]
Estimated story points: 5

# Description
 
As a user I want to create different payment levels for e.g. default and increased payment levels. Every payment level has a name.

 

# Acceptance criteria

Payment Levels can be created, edited and deleted.

**Comment by lukasschreiber** [comment]
Also die sollen wirklich nur einen Namen haben? Und wo sollen die bearbeitet werden können? Auf einer eigenen Seite oder soll das irgendwo dazu?

**Comment by mohe2015** [comment]
> Also die sollen wirklich nur einen Namen haben? Und wo sollen die bearbeitet werden können? Auf einer eigenen Seite oder soll das irgendwo dazu?

I think the payment levels should really only be a name like "Basiszahlung" or "erhöhte Vergütung". Then there are the https://github.com/reform-org/reform/issues/84 that reference these payment levels.

Please don't start implementing yet because we should wait for the refactor of the pages (https://github.com/reform-org/reform/pull/95)

**Comment by lukasschreiber** [comment]
ok

**Comment by lukasschreiber** [comment]
Verstehe die US nach wie vor nicht. Was soll das denn können? Wenn es nur zwei values geben soll und die vorher bekannt sind (gibt ja nur zwei payment level) warum muss man die bearbeiten können und warum macht man das nicht einfach als enum oder so?

**Comment by lukasschreiber** [comment]
Oder soll das einfach eine Seite sein wie die Hiwi Seite zum Beispiel und dann halt einfach nur ein attribut?

**Comment by lukasschreiber** [comment]
time: 1h

**Comment by mohe2015** [comment]
> 

Soll zukünftig theoretisch auch mehr Payment level können und denke mit einer Liste an Payment Leveln ist das die cleanste Abstraktion und passt halt auch in das ganze CRUD system rein
