### ISSUE TITLE
[US] CRUD for Salary Changes

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#84]
Estimated story points: 8

# Description
 
As a user I want to update the salary associated with a payment level. You can set the payment level starting with a specific date.

 

# Acceptance criteria

The salary level can be updated for an associated payment level. All related calculations are updated too then.

**Comment by lukasschreiber** [comment]
das wissen wir auch noch nicht genau. Idee ist aber, dass es wie die anderen seiten auch eine liste an stundenlöhnen sind (also einfach ein zahlenfeld (mit kommazahlen) für €/h. aber das spannende ist, dass jeder eintrag mit einem eintrag aus der payment level liste (die lukas gerade implementiert hat) verknüpft werden kann (vmtl mit einem dropdown) (wobei bei der verknüpfung die ID und nicht der angezeigte Name genommen werden muss). Und dann kann man halt für alle Bezahllevel Gehaltsänderungen einpflegen. Achso ein gültigkeitsdatum muss auch noch zu jedem eintrag dazu
