### ISSUE TITLE
[US] CRUD for required documents

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#86]
Estimated story points: 8

# Description
 
As a user I want to associate required documents with a contract type. Every required document has a name, a file and a boolean whether its also required for contract extensions.

 

# Acceptance criteria

Required documents can be created, edited and deleted.

**Comment by Oshgnacknak** [comment]
> and a boolean whether its also required for contract extensions

What does it mean for "required documents" to not be required? Maybe their name is misleading

**Comment by mohe2015** [comment]
> > and a boolean whether its also required for contract extensions
> 
> What does it mean for "required documents" to not be required? Maybe their name is misleading

I think originally I planned to say one contract type consists of a "new contract" possibility and an "extend contract" possibility and not all documents are needed for the "extend contract". But I think it would be nicer if you just have two contract types one for new contract and one for extend contract.

The checkboxes are still needed to actually check off documents for each specific contract.

**Comment by mohe2015** [comment]
Closed by https://github.com/reform-org/reform/pull/185
