### ISSUE TITLE
[US] CRUD for contract (drafts)

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#87]
Estimated story points: 21

# Description
 
As a user I want to create contracts consisting of an associated contract type, associated hiwi, an associated supervisor, a contract start date, a contract end date, hours per month and an associated payment level. There also is a boolean which marks it as a draft. A contract has an associated list of required documents that can be checked. Also there is an optional reference to a previous contract in which case it is a contract extension.

 

# Acceptance criteria

Contracts can be created, edited and deleted.

**Comment by lukasschreiber** [comment]
Bist du hier dran @mohe2015 oder soll das lieber jmd machen, der noch mehr Stunden braucht? Habe in der Liste von offenen issues gesehen, bei denen es wichtiger wäre, dass du das machst.

**Comment by mohe2015** [comment]
> Bist du hier dran @mohe2015 oder soll das lieber jmd machen, der noch mehr Stunden braucht? Habe in der Liste von offenen issues gesehen, bei denen es wichtiger wäre, dass du das machst.

Hab mich unassigned.

**Comment by mohe2015** [comment]
Remaining things should be tracked in https://github.com/reform-org/reform/issues/259
