### ISSUE TITLE
[US] Templating for contract and letter to deanship

### ISSUE THREAD

**Issue by mohe2015** [reform-org/reform#88]
Estimated story points: 13

# Description
 

 

# Acceptance criteria

**Comment by lukasschreiber** [comment]
Was meint hier templating? Dachte es geht um das Ausfüllen von PDFs, da sollte doch das Erstellen von Templates keine Rolle mehr spielen, oder?

**Comment by mohe2015** [comment]
> Was meint hier templating? Dachte es geht um das Ausfüllen von PDFs, da sollte doch das Erstellen von Templates keine Rolle mehr spielen, oder?

Yeah I just called that templating. The implementation details should be filling pdf forms but we should probably ask for the updated documents first to see exactly what's needed. I also remember one word document with a table so lets find out then how much work this is gonna be.

**Comment by lukasschreiber** [comment]
okay, finde es super weird, dass wir uns auf Englisch unterhalten xD ich schreibe Ragnar dann morgen mal zu einer humaneren Uhrzeit an.

**Comment by mohe2015** [comment]
> okay, finde es super weird, dass wir uns auf Englisch unterhalten xD ich schreibe Ragnar dann morgen mal zu einer humaneren Uhrzeit an.

The user stories are in english so I write in english. But sounds good

**Comment by lukasschreiber** [comment]
time: 7h
